apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mariadb-single.fullname" . }}-config
  labels:
    {{- include "mariadb-single.labels" . | nindent 4 }}
data:
  my.cnf: |
{{ .Values.config.myCnf | nindent 4 }}